function loadDemo(){
  enter();
  if(state.nodes.length&&!confirm('Aggiungere la storia demo alle tracce già presenti?'))return;
  state.nodes=state.nodes.filter(n=>!String(n.id).startsWith('demo-'));
  state.connections=state.connections.filter(c=>!String(c.from).startsWith('demo-')&&!String(c.to).startsWith('demo-'));
  const demo=[
    {id:'demo-child-birth',title:'La nascita di mio figlio',text:'Il giorno in cui sono diventato padre. Il centro della vita ha cambiato posizione.',type:'Ricordo',emotion:'Amore',intensity:10,meaning:'Mi ha cambiato',date:'2024-04-14',eventSize:'Grande',tags:['figlio','famiglia','nascita','padre'],a:.18,r:145,z:-120},
    {id:'demo-father',title:'Imparare a essere padre',text:'Una nuova identità che cresce tra responsabilità, paura e meraviglia.',type:'Persona',emotion:'Speranza',intensity:9,meaning:'Mi ha formato',date:'2024-04-15',eventSize:'Grande',tags:['figlio','famiglia','padre','crescita'],a:.82,r:220,z:80},
    {id:'demo-bedtime',title:'La routine della buonanotte',text:'Una piccola abitudine quotidiana che col tempo diventa memoria condivisa.',type:'Routine',emotion:'Serenità',intensity:7,meaning:'Fa parte di me',date:'2026-07-20',eventSize:'Piccolo',tags:['figlio','famiglia','routine','sera'],a:1.55,r:300,z:-250},
    {id:'demo-work-city',title:'Il lavoro in città',text:'Responsabilità, crescita professionale e la sensazione di dover tenere insieme molti fili.',type:'Sfida',emotion:'Orgoglio',intensity:8,meaning:'Mi ha formato',date:'2025-01-20',eventSize:'Grande',tags:['lavoro','città','carriera','pressione'],a:2.18,r:260,z:160},
    {id:'demo-traffic',title:'Il traffico quotidiano',text:'Tempo perso, stanchezza e rientri più tardi del previsto.',type:'Routine',emotion:'Rabbia',intensity:7,meaning:'Mi ha insegnato',date:'2025-02-03',eventSize:'Medio',tags:['lavoro','traffico','pressione','tempo'],a:2.78,r:355,z:280},
    {id:'demo-bonus',title:'Un riconoscimento economico importante',text:'Il risultato concreto di un lavoro complesso e di una responsabilità sostenuta nel tempo.',type:'Obiettivo',emotion:'Orgoglio',intensity:8,meaning:'Mi ha insegnato',date:'2026-03-28',eventSize:'Medio',tags:['lavoro','successo','riconoscimento','futuro'],a:3.34,r:330,z:-80},
    {id:'demo-waterpolo',title:'Lo sport di squadra come parte di me',text:'Non soltanto sport: disciplina, identità, squadra e capacità di resistere.',type:'Persona',emotion:'Nostalgia',intensity:9,meaning:'Fa parte di me',date:'2024-09-02',eventSize:'Grande',tags:['sport','squadra','disciplina','identità'],a:3.92,r:245,z:-190},
    {id:'demo-team-win',title:'La vittoria della squadra',text:'Una vittoria costruita insieme, capace di restituire fiducia anche a chi guida il gruppo.',type:'Sfida',emotion:'Orgoglio',intensity:9,meaning:'Mi ha insegnato',date:'2026-05-17',eventSize:'Grande',tags:['sport','squadra','vittoria','fiducia'],a:4.48,r:315,z:130},
    {id:'demo-child-difficulty',title:'Una giornata difficile con mio figlio',text:'Stanchezza, incomprensione e il timore di non riuscire sempre a essere il padre che vorrei.',type:'Paura',emotion:'Tristezza',intensity:8,meaning:'Mi ha ferito',date:'2026-06-09',eventSize:'Medio',tags:['figlio','famiglia','pressione','difficoltà'],a:5.04,r:285,z:250},
    {id:'demo-couple-tension',title:'Una tensione di coppia',text:'Quando lavoro, stanchezza e responsabilità familiari arrivano nello stesso punto.',type:'Sfida',emotion:'Rabbia',intensity:7,meaning:'Mi ha insegnato',date:'2026-06-11',eventSize:'Medio',tags:['coppia','famiglia','pressione','lavoro'],a:5.56,r:345,z:-20},
    {id:'demo-future',title:'Il futuro che vorrei lasciare a mio figlio',text:'Uno spazio in cui possa ricordare da dove viene senza sentirsi definito dal passato.',type:'Sogno',emotion:'Speranza',intensity:10,meaning:'Mi chiama ancora',date:'2026-07-26',eventSize:'Grande',tags:['figlio','famiglia','futuro','sogno'],a:6.05,r:390,z:30}
  ].map(normalizeNode);
  state.nodes.push(...demo);
  const rels=[
    ['demo-child-birth','demo-father','Padre / figlio'],
    ['demo-father','demo-bedtime','È causa di'],
    ['demo-father','demo-child-difficulty','Contrasta con'],
    ['demo-child-difficulty','demo-couple-tension','È collegato a'],
    ['demo-work-city','demo-traffic','È causa di'],
    ['demo-work-city','demo-bonus','È causa di'],
    ['demo-traffic','demo-couple-tension','È conseguenza di'],
    ['demo-waterpolo','demo-team-win','È causa di'],
    ['demo-team-win','demo-father','Mi ha fatto crescere'],
    ['demo-child-birth','demo-future','Obiettivo nato da'],
    ['demo-bedtime','demo-future','Mi ha fatto crescere'],
    ['demo-bonus','demo-future','È collegato a']
  ];
  rels.forEach(([from,to,type])=>state.connections.push(normalizeConnection({from,to,type})));
  save();renderFilters();renderList();updateSearch();updateTimelineBounds();updateStatus();
  toast('Showcase pubblico caricato.');
  document.dispatchEvent(new CustomEvent('aevum:demo-loaded'));
}
function updateModeUI(){const deep=state.mode==='deep';$('modeBtn').innerHTML=deep?'◎ <span class="word">Orbita</span>':'◈ <span class="word">Deep</span>';$('deepBadge').classList.toggle('show',deep);updateStatus();save()}function toggleMode(){enter();state.mode=state.mode==='deep'?'orbit':'deep';state.targetX=0;state.targetY=0;state.targetZoom=state.mode==='deep'?.92:1;updateModeUI()}function updateTimelineBounds(){const years=state.nodes.map(n=>Number(String(n.date||'').slice(0,4))).filter(Number.isFinite),input=$('timelineRange');if(!years.length){input.min=0;input.max=0;input.value=0;$('timelineLabel').textContent='Tutto';return}const min=Math.min(...years),max=Math.max(...years);input.min=min;input.max=max;input.value=state.timelineYear||max;$('timelineLabel').textContent=state.timelineYear||'Tutto'}function setTimeline(value){state.timelineYear=value?Number(value):null;$('timelineLabel').textContent=state.timelineYear||'Tutto';updateStatus()}function selectChoice(group,value){document.querySelectorAll(`#${group} .choice`).forEach(b=>b.classList.toggle('on',b.dataset.value===value))}function choiceValue(group){return document.querySelector(`#${group} .choice.on`)?.dataset.value}function openGuided(){enter();closePanels();$('gTitle').value='';$('gTags').value='';selectChoice('gTypeChoices','Ricordo');selectChoice('gSizeChoices','Medio');$('guidedModal').classList.add('open');setTimeout(()=>$('gTitle').focus(),80)}function closeGuided(){$('guidedModal').classList.remove('open')}function continueGuided(){const title=$('gTitle').value.trim();if(!title){toast('Scrivi ciò che sta lasciando una traccia');return}closeGuided();openForm();$('title').value=title;$('type').value=choiceValue('gTypeChoices')||'Ricordo';$('eventSize').value=choiceValue('gSizeChoices')||'Medio';$('tags').value=$('gTags').value.trim();$('text').focus()}document.querySelectorAll('.choice').forEach(b=>b.addEventListener('click',()=>selectChoice(b.parentElement.id,b.dataset.value)));$('guidedBtn').addEventListener('click',openGuided);$('guidedCancel').addEventListener('click',closeGuided);$('guidedContinue').addEventListener('click',continueGuided);$('guidedModal').addEventListener('click',e=>{if(e.target===$('guidedModal'))closeGuided()});$('modeBtn').addEventListener('click',toggleMode);$('timelineRange').addEventListener('input',e=>setTimeline(e.target.value));$('timelineAll').addEventListener('click',()=>{state.timelineYear=null;updateTimelineBounds();$('timelineLabel').textContent='Tutto';updateStatus()});
$('enterBtn').addEventListener('click',enter);$('demoBtn').addEventListener('click',loadDemo);$('addBtn').addEventListener('click',()=>openForm());$('archiveAdd').addEventListener('click',()=>openForm());$('archiveBtn').addEventListener('click',()=>{renderFilters();renderList();openPanel('archive')});$('centerBtn').addEventListener('click',center);$('zoomIn').addEventListener('click',()=>state.targetZoom=Math.min(2.1,state.targetZoom+.18));$('zoomOut').addEventListener('click',()=>state.targetZoom=Math.max(.58,state.targetZoom-.18));$('clearSearch').addEventListener('click',()=>{$('searchInput').value='';state.query='';updateSearch();renderList();$('searchInput').focus()});$('searchInput').addEventListener('input',e=>{enter();state.query=e.target.value;updateSearch();renderList()});$('sortSelect').addEventListener('change',e=>{state.sort=e.target.value;renderList()});$('saveBtn').addEventListener('click',saveForm);$('cancelBtn').addEventListener('click',closeForm);$('modal').addEventListener('click',e=>{if(e.target===$('modal'))closeForm()});$('editBtn').addEventListener('click',()=>openForm(state.selected));$('deleteBtn').addEventListener('click',deleteSelected);$('focusBtn').addEventListener('click',focusSelected);$('addRelationBtn').addEventListener('click',addRelation);$('exportBtn').addEventListener('click',exportData);$('importBtn').addEventListener('click',()=>$('file').click());$('file').addEventListener('change',e=>{if(e.target.files[0])importData(e.target.files[0]);e.target.value=''});
canvas.addEventListener('pointerdown',e=>{enter();state.drag=true;state.lx=e.clientX;state.ly=e.clientY;state.moved=0});canvas.addEventListener('pointermove',e=>{if(!state.drag)return;const mx=e.clientX-state.lx,my=e.clientY-state.ly;state.moved+=Math.abs(mx)+Math.abs(my);if(state.mode==='deep'){state.targetRotY+=mx*.006;state.targetRotX=Math.max(-1.2,Math.min(1.2,state.targetRotX+my*.006))}else{state.targetX+=mx/state.zoom;state.targetY+=my/state.zoom}state.lx=e.clientX;state.ly=e.clientY});canvas.addEventListener('pointerup',e=>{if(!state.drag)return;state.drag=false;if(state.moved<12){let hit=null,best=Infinity;state.nodes.filter(visibleByTime).forEach(n=>{const p=nodePosition(n),factor=sizeScale[n.eventSize]||1,r=(16+n.intensity*.8)*factor*(p.depth||1),d=Math.hypot(e.clientX-p.x,e.clientY-p.y);if(d<r&&d<best){hit=n;best=d}});if(hit)showDetail(hit.id)}});canvas.addEventListener('pointercancel',()=>state.drag=false);
renderFilters();renderList();updateSearch();updateTimelineBounds();updateModeUI();updateStatus();if('serviceWorker'in navigator){addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
const showcaseScript=document.createElement('script');showcaseScript.src='./showcase.js';showcaseScript.defer=true;document.body.appendChild(showcaseScript);
