function enter(){$('hero').classList.add('hide');updateStatus()}
function updateStatus(){const mode=state.mode==='deep'?'Deep Space':'Orbita',time=state.timelineYear?` · fino al ${state.timelineYear}`:'';if(state.query){$('status').textContent=state.direct.size?`${mode}${time} · “${state.query}”: ${state.direct.size} tracce dirette e ${state.related.size} collegate.`:`${mode}${time} · nessuna traccia contiene “${state.query}”.`}else if(state.focus){const n=state.nodes.find(x=>x.id===state.focus);$('status').textContent=n?`${mode}${time} · fuoco su “${n.title}”.`:`${mode}${time} · Core ricentrato.`}else{$('status').textContent=state.nodes.length?`${mode}${time} · ${state.nodes.length} tracce · ${state.connections.length} connessioni vive.`:`${mode}${time} · il Core attende il primo battito.`}}
function openPanel(id){enter();['archive','detail'].forEach(x=>$(x).classList.toggle('open',x===id))}function closePanels(){['archive','detail'].forEach(x=>$(x).classList.remove('open'))}document.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',()=>$(b.dataset.close).classList.remove('open')));
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
function renderFilters(){const values=['Tutte',...Object.keys(colors)];$('filters').innerHTML='';values.forEach(v=>{const b=document.createElement('button');b.className='chip'+(state.filter===v?' on':'');b.textContent=v;b.addEventListener('click',()=>{state.filter=v;renderFilters();renderList()});$('filters').appendChild(b)})}
function sortedNodes(){let arr=state.nodes.filter(n=>state.filter==='Tutte'||n.type===state.filter);const q=state.query.trim().toLocaleLowerCase('it');if(q)arr=arr.filter(n=>state.direct.has(n.id)||state.related.has(n.id));arr=[...arr];if(state.sort==='date-desc')arr.sort((a,b)=>String(b.date).localeCompare(String(a.date)));if(state.sort==='date-asc')arr.sort((a,b)=>String(a.date).localeCompare(String(b.date)));if(state.sort==='size-desc')arr.sort((a,b)=>(sizeOrder[b.eventSize]||2)-(sizeOrder[a.eventSize]||2)||String(b.date).localeCompare(String(a.date)));if(state.sort==='title')arr.sort((a,b)=>a.title.localeCompare(b.title,'it'));return arr}
function renderList(){const list=$('list'),arr=sortedNodes();list.innerHTML='';if(!arr.length){list.innerHTML='<div class="empty">Nessuna traccia in questa vista.</div>';return}arr.forEach(n=>{const b=document.createElement('button');b.className='trace';const relationCount=state.connections.filter(c=>c.from===n.id||c.to===n.id).length;b.innerHTML=`<i style="color:${colors[n.type]||'#fff'};background:currentColor"></i><span><strong>${escapeHtml(n.title)}</strong><small>${formatDate(n.date)} · ${escapeHtml(n.type)} · ${relationCount} connessioni</small></span><span class="sizebadge">${escapeHtml(n.eventSize)}</span>`;b.addEventListener('click',()=>showDetail(n.id));list.appendChild(b)})}
function relationLabel(c,nodeId){const otherId=c.from===nodeId?c.to:c.from,other=state.nodes.find(n=>n.id===otherId);return{other,type:c.type}}
function relationRow(c,nodeId){const otherId=c.from===nodeId?c.to:c.from,other=state.nodes.find(n=>n.id===otherId);if(!other)return null;const row=document.createElement('div');row.className='connection';row.innerHTML=`<button style="all:unset;cursor:pointer"><strong>${escapeHtml(other.title)}</strong><small>${escapeHtml(c.type)}</small></button><button aria-label="Rimuovi connessione">×</button>`;row.firstElementChild.addEventListener('click',()=>showDetail(other.id));row.lastElementChild.addEventListener('click',()=>{state.connections=state.connections.filter(x=>x.id!==c.id);save();renderRelations(nodeId);renderList();showDetail(nodeId);toast('Connessione rimossa')});return row}
function renderRelations(nodeId){const roots=$('roots'),branches=$('branches');roots.innerHTML='';branches.innerHTML='';const rootRels=state.connections.filter(c=>c.to===nodeId),branchRels=state.connections.filter(c=>c.from===nodeId);if(!rootRels.length)roots.innerHTML='<div class="empty">Nessuna radice dichiarata.</div>';if(!branchRels.length)branches.innerHTML='<div class="empty">Nessun ramo dichiarato.</div>';rootRels.forEach(c=>{const row=relationRow(c,nodeId);if(row)roots.appendChild(row)});branchRels.forEach(c=>{const row=relationRow(c,nodeId);if(row)branches.appendChild(row)});const select=$('relationTarget');select.innerHTML='<option value="">Scegli una traccia…</option>';state.nodes.filter(n=>n.id!==nodeId&&!state.connections.some(c=>(c.from===nodeId&&c.to===n.id)||(c.to===nodeId&&c.from===n.id))).forEach(n=>{const o=document.createElement('option');o.value=n.id;o.textContent=`${n.title} · ${formatDate(n.date)}`;select.appendChild(o)})}
function showDetail(id){const n=state.nodes.find(x=>x.id===id);if(!n)return;state.selected=id;$('dType').textContent=n.type;$('dTitle').textContent=n.title;$('dText').textContent=n.text||'Nessun racconto aggiunto.';$('dDate').textContent=fullDate(n.date);$('dSize').textContent=n.eventSize;$('dEmotion').textContent=n.emotion;$('dIntensity').textContent=`${n.intensity}/10`;$('dMeaning').textContent=n.meaning;$('dConnections').textContent=state.connections.filter(c=>c.from===id||c.to===id).length;$('dTags').innerHTML=n.tags.length?n.tags.map(t=>`<span class="tag">${escapeHtml(t)}</span>`).join(''):'<span class="tag">Nessuna parola</span>';renderRelations(id);openPanel('detail');updateStatus()}
function resetForm(){$('editId').value='';$('formTitle').textContent='Aggiungi vita';$('title').value='';$('text').value='';$('date').value=today();$('eventSize').value='Medio';$('type').value='Ricordo';$('emotion').value='Gioia';$('intensity').value='7';$('meaning').value='Mi ha formato';$('tags').value=''}
function openForm(id=null){enter();closePanels();resetForm();if(id){const n=state.nodes.find(x=>x.id===id);if(!n)return;$('editId').value=n.id;$('formTitle').textContent='Modifica la traccia';$('title').value=n.title;$('text').value=n.text;$('date').value=n.date;$('eventSize').value=n.eventSize;$('type').value=n.type;$('emotion').value=n.emotion;$('intensity').value=n.intensity;$('meaning').value=n.meaning;$('tags').value=n.tags.join(', ')}$('modal').classList.add('open');setTimeout(()=>$('title').focus(),80)}
function closeForm(){$('modal').classList.remove('open')}
function saveForm(){const title=$('title').value.trim();if(!title){toast('Inserisci un titolo');$('title').focus();return}const id=$('editId').value,existing=state.nodes.find(n=>n.id===id),node=normalizeNode({...existing,id:id||uid(),title,text:$('text').value.trim(),date:$('date').value||today(),eventSize:$('eventSize').value,type:$('type').value,emotion:$('emotion').value,intensity:Number($('intensity').value),meaning:$('meaning').value,tags:normalizeTags($('tags').value),a:existing?.a??Math.random()*Math.PI*2,r:existing?.r??110+Math.random()*Math.min(330,Math.max(150,innerWidth*.42)),createdAt:existing?.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString()});if(existing)state.nodes=state.nodes.map(n=>n.id===id?node:n);else state.nodes.push(node);state.selected=node.id;save();closeForm();renderFilters();renderList();updateSearch();updateTimelineBounds();showDetail(node.id);toast(existing?'Traccia aggiornata':'Nuova traccia nel Core')}
function deleteSelected(){if(!state.selected)return;const n=state.nodes.find(x=>x.id===state.selected);if(!n)return;if(!confirm(`Eliminare “${n.title}” e le sue connessioni?`))return;state.nodes=state.nodes.filter(x=>x.id!==state.selected);state.connections=state.connections.filter(c=>c.from!==state.selected&&c.to!==state.selected);state.selected=null;state.focus=null;save();closePanels();renderFilters();renderList();updateSearch();updateTimelineBounds();updateStatus();toast('Traccia eliminata')}
function addRelation(){const selected=state.selected,target=$('relationTarget').value,type=$('relationType').value,direction=$('relationDirection').value;if(!selected||!target){toast('Scegli una traccia da collegare');return}const from=direction==='root'?target:selected,to=direction==='root'?selected:target;if(state.connections.some(c=>(c.from===from&&c.to===to)||(c.from===to&&c.to===from))){toast('Le tracce sono già collegate');return}state.connections.push(normalizeConnection({from,to,type}));save();renderRelations(selected);renderList();showDetail(selected);updateSearch();toast(direction==='root'?'Radice creata':'Ramo creato')}
function center(){state.targetX=0;state.targetY=0;state.targetZoom=1;state.targetRotX=-.12;state.targetRotY=.15;state.focus=null;updateStatus()}
function focusSelected(){const n=state.nodes.find(x=>x.id===state.selected);if(!n)return;const p=nodePosition(n);state.targetX+=(state.W/2-p.x)/state.zoom;state.targetY+=(state.H/2-p.y)/state.zoom;state.targetZoom=Math.min(1.75,Math.max(1.2,state.targetZoom));state.focus=n.id;closePanels();updateStatus()}
function exportData(){const blob=new Blob([JSON.stringify({app:'Aevum Core',version:'0.6',exportedAt:new Date().toISOString(),nodes:state.nodes,connections:state.connections},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`aevum-core-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);toast('Archivio esportato')}
function importData(file){const reader=new FileReader();reader.onload=()=>{try{const data=JSON.parse(reader.result),nodes=Array.isArray(data)?data:data.nodes;if(!Array.isArray(nodes))throw new Error('Formato non valido');state.nodes=nodes.map(normalizeNode);state.connections=(data.connections||[]).map(normalizeConnection).filter(c=>state.nodes.some(n=>n.id===c.from)&&state.nodes.some(n=>n.id===c.to));save();renderFilters();renderList();updateSearch();updateTimelineBounds();updateStatus();toast('Archivio importato')}catch(err){toast('File non valido')}};reader.readAsText(file)}
